FROM oraclelinux:8.6
RUN dnf -y install rpmdevtools rpm-build rpm-sign gcc openssl-devel pkg-config zsh
RUN adduser -c "RPM build user" -s /bin/zsh -m rpmbuilder

USER rpmbuilder 
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  -s -- --profile minimal -y
