include:
  - project: "ds_2/ci-templates"
    ref: v0.1.19-alpha.1
    file:
      - "/templates/stages.yaml"
      - "/templates/global-vars.yaml"
      - "/templates/build-kaniko.yaml"

rust-alma9:
  extends: .build-with-kaniko
  variables:
    CTX_DIR: enterpriselinux-rust
    BUILD_ARGS: "linuxDistro=almalinux distroVersion=9"
    ADDITIONALTAGLIST: "alma9"

rust-ol8:
  extends: .build-with-kaniko
  variables:
    CTX_DIR: enterpriselinux-rust
    ADDITIONALTAGLIST: "ol8"
    BUILD_ARGS: "linuxDistro=oraclelinux distroVersion=8"

rust-ubuntu-jammy:
  extends: .build-with-kaniko
  variables:
    CTX_DIR: rust-debian
    BUILD_ARGS: "linuxDistro=ubuntu distroVersion=jammy"
    ADDITIONALTAGLIST: "jammy bw"

rust-debian-bookworm:
  extends: .build-with-kaniko
  variables:
    CTX_DIR: rust-debian
    BUILD_ARGS: "linuxDistro=debian distroVersion=bookworm"
    ADDITIONALTAGLIST: "bookworm bw"

############################## DEPLOY TO OUR REPO #########################

deploy-rust-alma9:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: enterpriselinux-rust
    BUILD_ARGS: "linuxDistro=almalinux distroVersion=9"
    ADDITIONALTAGLIST: "alma9"

deploy-rust-debian-bookworm:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: rust-debian
    BUILD_ARGS: "linuxDistro=debian distroVersion=bookworm"
    ADDITIONALTAGLIST: "bookworm bw"
