include:
  - project: "ds_2/ci-templates"
    ref: v0.1.20-alpha.1
    file:
      - "/templates/stages.yaml"
      - "/templates/global-vars.yaml"
      - "/templates/build-kaniko.yaml"

############################## DEPLOY TO OUR REPO #########################

deploy-packagecloud:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: package-cloud
    ADDITIONALTAGLIST: "pkgcld"
    QUAY_IO_EXPIRY: "1y"
