include:
  - project: "ds_2/ci-templates"
    ref: v3.1.2
    file:
      - "/templates/stages.yaml"
      - "/templates/global-vars.yaml"
      - "/templates/build-buildah.yaml"
      - "/templates/release-marker.yaml"

############################## Test Image Building ########################
build-packagecloud:
  extends: .build-with-buildah
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    CTX_DIR: package-cloud

build-payara-jndi-web:
  extends: .build-with-buildah
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    CTX_DIR: payara-jndi
    DKR_FILE: Dockerfile
    BUILD_ARGS: "BASE_IMAGE=server-web"

build-payara-jndi-full:
  extends: .build-with-buildah
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    CTX_DIR: payara-jndi
    DKR_FILE: Dockerfile
    BUILD_ARGS: "BASE_IMAGE=server-full"

# build-latex:
#   extends: .build-with-buildah
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#   variables:
#     CTX_DIR: latex
#     Dockerfile: Dockerfile
#     ADDITIONALTAGLIST: "staging"
#     QUAY_IO_EXPIRY: "1w"

############################## DEPLOY TO OUR REPO #########################

deploy-packagecloud:
  extends: .deploy-with-buildah
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    CTX_DIR: package-cloud
    ADDITIONALTAGLIST: "pkgcld"
