include:
  - project: "ds_2/ci-templates"
    ref: v0.1.19-alpha.1
    file:
      - "/templates/stages.yaml"
      - "/templates/global-vars.yaml"
      - "/templates/build-kaniko.yaml"


rust-ubuntu-jammy:
  extends: .build-with-kaniko
  variables:
    CTX_DIR: rust-debian
    BUILD_ARGS: "linuxDistro=ubuntu distroVersion=jammy"
    ADDITIONALTAGLIST: "jammy jm"


############################## DEPLOY TO OUR REPO #########################

deploy-rust-alma9:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: enterpriselinux-rust
    BUILD_ARGS: "linuxDistro=almalinux distroVersion=9"
    ADDITIONALTAGLIST: "alma9"

deploy-rust-ol8:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: enterpriselinux-rust
    BUILD_ARGS: "linuxDistro=oraclelinux distroVersion=8"
    ADDITIONALTAGLIST: "ol8"

deploy-rust-debian-bookworm:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: rust-debian
    BUILD_ARGS: "linuxDistro=debian distroVersion=bookworm"
    ADDITIONALTAGLIST: "bookworm bw"

deploy-rust-debian-bullseye:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: rust-debian
    BUILD_ARGS: "linuxDistro=debian distroVersion=bullseye semverUrl=https://ds2linuxrepo.blob.core.windows.net/bullseye/semver-formatter_0.4.0-alpha.1.b5180223.builddate-202306081541_amd64.deb"
    ADDITIONALTAGLIST: "bullseye be"

deploy-packagecloud:
  extends: .deploy-with-kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    CTX_DIR: package-cloud
    ADDITIONALTAGLIST: "pkgcld"
