FROM node:18
ARG WITH_COREPACK=1
EXPOSE 8888
# set NODE_ENV # development, production
ENV NODE_ENV=development

# install tools
USER root
RUN npm version
RUN if [ ${WITH_COREPACK} -eq 1 ]; then echo "enable corepack.."; corepack enable; fi
RUN npm install -g yarn; yarn set version berry; yarn set version stable
RUN npm install -g @angular/cli

# setup runtime
USER node
WORKDIR /src
RUN yarn --version
RUN ng version
RUN npx --version
