FROM alpine:3.17.4
ENV TZ=Etc/UTC
ENV RUST_BACKTRACE=1
ENV LC_ALL=de_DE.UTF-8
ENV TZ=Etc/UTC

# prepare image
RUN apk update -y; apk upgrade
RUN apk add zsh sudo git vim curl unzip rsync py3-pip protobuf # protobuf-compiler python3-pip vim curl unzip pre-commit lsb-release pkg-config rsync
RUN adduser -s /bin/zsh -D rusty
ADD sudoers.txt /etc/sudoers.d/rusty

# set language
#RUN apt-get install -y lsb-release locales; locale-gen en_US.UTF-8; locale-gen de_DE.UTF-8; echo en_US UTF-8 >> /etc/locale.gen; echo de_DE UTF-8 >> /etc/locale.gen; dpkg-reconfigure locales

# install protoc
RUN protoc --version

# install MS SBOM tool
# RUN curl -Lo /usr/local/bin/sbom-tool https://github.com/microsoft/sbom-tool/releases/download/v1.1.5/sbom-tool-linux-x64; chmod a+x /usr/local/bin/sbom-tool
# RUN sbom-tool version

# setup user environment (we do not run as root!!)
USER rusty
WORKDIR /tmp
ENV CARGO_BUILD_TARGET='x86_64-unknown-linux-gnu'

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  -s -- --profile minimal --no-modify-path -y
RUN . ~/.cargo/env; cargo version

RUN pip3 install --user pre-commit || true
RUN pip3 install --user --break-system-packages pre-commit || true
RUN /home/rusty/.local/bin/pre-commit --version

# prepare runs
ENV GNUPGHOME_ALT=/home/rusty/gnupg-alt
ADD --chown=rusty:users zshrc.txt /home/rusty/.zshrc
ENV CARGO_HOME=/home/rusty/.cargo
ENV PERFORM_CLEAN_TARGET=0
ENV CARGO_TARGET_DIR=target
ENV SUDO_CLEAN_TARGET=0
RUN mv ~/.cargo/env ~/.cargo/env.orig; echo "" >~/.cargo/env

USER root
COPY entrypoint.sh /entrypoint.sh
COPY createPackage.sh /usr/local/bin/
#RUN rm -rf /var/lib/apt/lists/* && apt-get purge --auto-remove && apt-get clean 

USER rusty
ENTRYPOINT [ "/entrypoint.sh" ]
WORKDIR /work
CMD [ "/bin/zsh" ]
