FROM docker.io/rust:1.75.0
RUN for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do apt-get remove $pkg -y || true; done
ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=de_DE.UTF-8
ENV TZ=Etc/UTC
RUN apt-get update -y; apt-get upgrade -y; \
    apt-get install -y ca-certificates curl gnupg lsb-release locales; \
    rm -rf /var/lib/apt/lists/* && apt-get purge --auto-remove && apt-get clean
RUN locale-gen en_US.UTF-8; locale-gen de_DE.UTF-8; echo en_US UTF-8 >> /etc/locale.gen; echo de_DE UTF-8 >> /etc/locale.gen; dpkg-reconfigure locales
RUN install -m 0755 -d /etc/apt/keyrings; curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg; chmod a+r /etc/apt/keyrings/docker.gpg
RUN echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update; apt-get install docker-ce-cli containerd.io -y
RUN docker --version
RUN rm -rf /var/lib/apt/lists/* && apt-get purge --auto-remove && apt-get clean
