ARG linuxDistro="debian"
ARG distroVersion="bookworm"
FROM ${linuxDistro}:${distroVersion}

ENV TZ=Etc/UTC
ENV RUST_BACKTRACE=1
ENV LC_ALL=de_DE.UTF-8
ENV TZ=Etc/UTC

# prepare image
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y; apt-get upgrade -y
RUN apt-get install -y zsh sudo git protobuf-compiler python3-pip vim curl unzip pre-commit lsb-release pkg-config rsync
RUN useradd -c "build user for Rust stuff" -g users -s /bin/zsh -m rusty
ADD sudoers.txt /etc/sudoers.d/rusty

RUN apt-get install -y lsb-release locales; locale-gen en_US.UTF-8; locale-gen de_DE.UTF-8; echo en_US UTF-8 >> /etc/locale.gen; echo de_DE UTF-8 >> /etc/locale.gen; dpkg-reconfigure locales

# install semver tool
ARG semverUrl=https://ds2linuxrepo.blob.core.windows.net/debian/semver-formatter_0.3.0-1_amd64.deb
#RUN curl -s https://packagecloud.io/install/repositories/lexxy23/releases/script.deb.sh | sudo bash; apt-get install -y semver-formatter
RUN curl -L -o /tmp/semver.deb ${semverUrl}; dpkg --install /tmp/semver.deb; rm /tmp/semver.deb
RUN semver-formatter -V

# install protoc
RUN protoc --version

# install MS SBOM tool
RUN apt-get install -y libicu72; curl -Lo /usr/local/bin/sbom-tool https://github.com/microsoft/sbom-tool/releases/download/v1.1.5/sbom-tool-linux-x64; chmod a+x /usr/local/bin/sbom-tool
RUN sbom-tool version

# setup user environment (we do not run as root!!)
USER rusty
WORKDIR /tmp
ENV CARGO_BUILD_TARGET='x86_64-unknown-linux-gnu'

# install rust
ARG rustVersion=stable
RUN export _RUST_VERSION=$rustVersion; curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  -s -- --default-toolchain ${_RUST_VERSION:-1.60.0} --profile minimal --no-modify-path -y
RUN . ~/.cargo/env; cargo version
RUN rm -rf ~/.rustup/tmp

RUN pip3 install --user pre-commit || true
RUN pip3 install --user --break-system-packages pre-commit || true
RUN pre-commit --version

# prepare runs
ENV GNUPGHOME_ALT=/home/rusty/gnupg-alt
ADD --chown=rusty:users zshrc.txt /home/rusty/.zshrc
ENV CARGO_HOME=/home/rusty/.cargo
ENV PERFORM_CLEAN_TARGET=0
ENV CARGO_TARGET_DIR=target
ENV SUDO_CLEAN_TARGET=0
RUN mv ~/.cargo/env ~/.cargo/env.orig; echo "" >~/.cargo/env

USER root
COPY entrypoint.sh /entrypoint.sh
COPY createDeb.sh /usr/local/bin/
RUN rm -rf /var/lib/apt/lists/* && apt-get purge --auto-remove && apt-get clean

USER rusty
ENTRYPOINT [ "/entrypoint.sh" ]
WORKDIR /work
CMD [ "/bin/zsh" ]
