CREATE GROUP dbadms NOLOGIN;
CREATE GROUP dbusers NOLOGIN;
CREATE GROUP dbreaders NOLOGIN;

CREATE USER dbadm LOGIN
    CONNECTION LIMIT 5
    PASSWORD 'dbadmpw' IN GROUP dbadms;

CREATE USER dbuser LOGIN
    CONNECTION LIMIT 5
    PASSWORD 'dbuserpw' IN GROUP dbusers;
CREATE USER dbreader LOGIN
    CONNECTION LIMIT 5
    PASSWORD 'dbreaderpw' IN GROUP dbreaders;

CREATE DATABASE mydb1 OWNER dbadm ENCODING 'utf8';
CREATE DATABASE mydb2 OWNER dbadm ENCODING 'utf8';

REVOKE ALL ON DATABASE mydb1 FROM PUBLIC;
REVOKE ALL ON DATABASE mydb2 FROM PUBLIC;

GRANT CONNECT ON DATABASE mydb1 TO dbadms;
GRANT CONNECT ON DATABASE mydb1 TO dbusers;
GRANT CONNECT ON DATABASE mydb1 TO dbreaders;

GRANT CONNECT ON DATABASE mydb2 TO dbadms;
GRANT CONNECT ON DATABASE mydb2 TO dbusers;
GRANT CONNECT ON DATABASE mydb2 TO dbreaders;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

--GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO dbadm;
