ARG linuxDistro=oraclelinux
ARG distroVersion=9
FROM ${linuxDistro}:${distroVersion}
RUN dnf update -y; dnf upgrade -y

RUN ls -l /etc/*-release
RUN cat /etc/*-release

# for OracleLinux 8:
RUN source /etc/os-release; if [ "$ORACLE_BUGZILLA_PRODUCT" = "Oracle Linux 8" ]; then dnf module enable go-toolset:ol8addon; dnf module install go-toolset; fi;

RUN dnf install go-toolset -y

RUN go version

# Additional deps
#RUN dnf install -y libvirt-devel protobuf rpm-build

# the fpm script to build RPMs
RUN dnf install ruby -y; gem install fpm

ENV LC_ALL=de_DE.UTF-8
RUN apt-get install -y lsb-release locales; locale-gen en_US.UTF-8; locale-gen de_DE.UTF-8; echo en_US UTF-8 >> /etc/locale.gen; echo de_DE UTF-8 >> /etc/locale.gen; dpkg-reconfigure locales

RUN rm -rf /var/lib/apt/lists/* && apt-get purge --auto-remove && apt-get clean

ENV TZ=Etc/UTC
WORKDIR /work
