FROM docker.io/ruby:4-alpine3.23
ARG UID=1000
RUN apk update && apk add --no-cache zsh bash
RUN adduser -S -u ${UID} -s /usr/bin/zsh -G wheel packager
RUN chmod +t /tmp
RUN ruby -v
RUN gem install package_cloud

RUN package_cloud version

USER packager
WORKDIR /work
RUN mkdir -p /home/packager/mytmp
ENV TMPDIR=/home/packager/mytmp
ENV TMP=/home/packager/mytmp
RUN package_cloud version
CMD [ "/bin/zsh" ]
