# also almalinux might be an idea?
# test 5
ARG linuxDistro=oraclelinux 
ARG distroVersion=9
FROM ${linuxDistro}:${distroVersion}
ENV TZ=Etc/UTC
ARG semverRpmVersion=0.1.1-rc.6

# prepare image
RUN dnf update -y
RUN dnf -y install rpmdevtools rpm-build rpm-sign gcc openssl-devel pkg-config zsh git sudo protobuf protobuf-compiler
RUN adduser -c "RPM build user for Rust stuff" -g users -G wheel -s /bin/zsh -m rusty
ADD sudoers.txt /etc/sudoers.d/rusty

# install semver tool
RUN curl -o /tmp/semver.rpm -L https://ds2linuxrepo.blob.core.windows.net/rpms/semver-formatter-${semverRpmVersion}.el8.x86_64.rpm; rpm -ihv /tmp/semver.rpm; semver-formatter -V

# install azure cli
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN export distroVersion=$(cat /etc/system-release-cpe | cut -d ':' -f5); echo "distroVersion is ${distroVersion}"; if [ $distroVersion == 9 ]; then dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm; elif [ $distroVersion == 8 ]; then sudo dnf install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm; else echo "No Distro installed??"; exit 23; fi; dnf update -y
RUN dnf list --showduplicates azure-cli; dnf -y install azure-cli

# install azcopy
RUN curl -o /tmp/azcopy.tgz -L https://aka.ms/downloadazcopy-v10-linux; cd /tmp; tar -xzvf /tmp/azcopy.tgz --strip 1; find /tmp; chmod 755 /tmp/azcopy; cp /tmp/azcopy /usr/bin/; azcopy --version

COPY createRpms.sh /usr/local/bin/

# setup user environment (we do not run as root!!)
USER rusty
WORKDIR /tmp
ENV CARGO_BUILD_TARGET='x86_64-unknown-linux-gnu'

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  -s -- --profile minimal -y
RUN source ~/.cargo/env; cargo version

# prepare runs
ADD --chown=rusty:users ZSHRC.txt /home/rusty/.zshrc
ENV CARGO_HOME=/home/rusty/.cargo
RUN mv ~/.cargo/env ~/.cargo/env.orig; echo "" >~/.cargo/env
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
WORKDIR /work
CMD [ "/bin/zsh" ]
