name: Test Dockerfile(s)
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  cicd_build8:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: cicd/build8
          push: false
          tags: cicd/build8:latest
