name: Test Dockerfile(s)
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image-matrix:
    name: Podman Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        containers:
          [
            { path: "cicd/bazel" },
            { path: "rust-dind" },
            { path: "node-yarn-fe-builder" },
            { path: "golang-ol8", tag: "ol8" },
            { path: "golang-ol8", buildArgs: "linuxDistro=almalinux \n
                distroVersion=9", tag: "alm9" },
            { path: "golang-ol8", buildArgs: "linuxDistro=almalinux \n
                distroVersion=8", tag: "alm8" },
            { path: "package-cloud" },
          ]
    steps:
      - name: checkout project ${{matrix.containers.path}}
        uses: actions/checkout@v4
      - name: Buildah Action
        id: build-image-buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.containers.repository || matrix.containers.path }}
          context: ./${{ matrix.containers.path }}
          tags: latest ${{ github.sha }} ${{matrix.containers.tag || ''}}
          build-args: ${{ matrix.containers.buildArgs || '' }}
          containerfiles: |
            ./${{ matrix.containers.path }}/Containerfile
          labels: |
            build_on:github

  cicd_build8:
    name: build cicd build8 image
    runs-on: ubuntu-latest
    env:
      REPO_PATH: cicd/build8
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
          # tags: ${env.REPO_PATH}:latest

  cicd_build17:
    name: build cicd build17 image
    runs-on: ubuntu-latest
    env:
      REPO_PATH: cicd/build17
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  terraform:
    name: build image terraform
    runs-on: ubuntu-latest
    env:
      REPO_PATH: terraform
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  payara-jndi-web:
    name: build image payara web
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "payara-jndi-web"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  payara-jndi-full:
    name: build image payara full
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "payara-jndi-full"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  k8s-fw:
    name: build image k8s filewatcher
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "kubernetes/filewatcher"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  k8s-ghar:
    name: build image k8s ghar
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "kubernetes/github-actionrunner"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  java11:
    name: build image java11 execjre
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "java11/exec-jre"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  java8:
    name: build image java8 execjre
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "java8/exec-jre"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  openjdk8:
    name: build image openjdk8 execjre
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "openjdk8/execjre"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  openjdk11:
    name: build image openjdk11 execjre
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "openjdk11/execjre"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  latex:
    name: build image latex
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "latex"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  cicd-jmeter:
    name: build image cicd jmeter
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "cicd/jmeter"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  cicd-tca11:
    name: build image cicd tca11
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "cicd/tca11"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
  cicd-jkslave:
    name: build image cicd jenkins
    runs-on: ubuntu-latest
    env:
      REPO_PATH: "cicd/tca11"
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.REPO_PATH}}
