name: Test Dockerfile(s)
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  cicd_build8:
    name: build cicd build8 image
    runs-on: ubuntu-latest
    env:
      REPO_PATH: cicd/build8
    steps:
      - name: checkout project ${{env.REPO_PATH}}
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image for ${{env.REPO_PATH}}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./${{env.REPO_PATH}}
          # tags: ${env.REPO_PATH}:latest
