name: publish to Quay

on:
  push:
    branches:
      - develop

jobs:
  publish-el9:
    name: Publish EL9
    runs-on: ubuntu-22.04
    env:
      path: "enterpriselinux-rust"
      registry: "quay.io"
      repository: "ds2/enterpriselinux-rust"
    steps:
      - name: checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: check modified files
        id: check_files
        run: |
          run_job=false
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo "checking file $file to be from ${{env.path}}"
            if [[ $file != ${{env.path}}/* ]]; then
              echo "ignoring.."
            else
              echo "found changes!"
              run_job=true
              break
            fi
          done < files.txt
          echo "Outcome will be set to: $run_job"
          echo "run_job=$run_job" >> $GITHUB_OUTPUT
      - name: Buildah Action
        id: build-image-buildah
        if: steps.check_files.outputs.run_job == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.repository }}
          context: ./${{ env.path }}
          tags: latest ol9-${{ github.sha }} ${{github.ref_name}} oraclelinux9
          build-args: |
            distroVersion=9
            linuxDistro=oraclelinux
          containerfiles: |
            ./${{ env.path }}/Containerfile
          labels: |
            build_on:github
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        if: ${{ env.registry && steps.build-image-buildah.outputs.image && steps.build-image-buildah.outcome == 'success' }}
        with:
          image: ${{ steps.build-image-buildah.outputs.image }}
          tags: ${{ steps.build-image-buildah.outputs.tags }}
          registry: ${{env.registry}}
          username: ${{ secrets.QUAY_IO_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_IO_REGISTRY_PASSWORD }}
      - name: Print image url
        if: ${{steps.push-to-quay.outcome == 'success'}}
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
  publish-el8:
    name: Publish EL8
    runs-on: ubuntu-22.04
    env:
      path: "enterpriselinux-rust"
      registry: "quay.io"
      repository: "ds2/enterpriselinux-rust"
    steps:
      - name: checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: check modified files
        id: check_files
        run: |
          run_job=false
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo "checking file $file to be from ${{env.path}}"
            if [[ $file != ${{env.path}}/* ]]; then
              echo "ignoring.."
            else
              echo "found changes!"
              run_job=true
              break
            fi
          done < files.txt
          echo "Outcome will be set to: $run_job"
          echo "run_job=$run_job" >> $GITHUB_OUTPUT
      - name: Buildah Action
        id: build-image-buildah
        if: steps.check_files.outputs.run_job == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.repository }}
          context: ./${{ env.path }}
          tags: ol8-${{ github.sha }} oraclelinux8
          build-args: |
            distroVersion=8
            linuxDistro=oraclelinux
          containerfiles: |
            ./${{ env.path }}/Containerfile
          labels: |
            build_on:github
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        if: ${{ env.registry && steps.build-image-buildah.outputs.image && steps.build-image-buildah.outcome == 'success' }}
        with:
          image: ${{ steps.build-image-buildah.outputs.image }}
          tags: ${{ steps.build-image-buildah.outputs.tags }}
          registry: ${{env.registry}}
          username: ${{ secrets.QUAY_IO_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_IO_REGISTRY_PASSWORD }}
      - name: Print image url
        if: ${{steps.push-to-quay.outcome == 'success'}}
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
  publish-alml9:
    name: Publish EL9 AlmaLinux
    runs-on: ubuntu-22.04
    env:
      path: "enterpriselinux-rust"
      registry: "quay.io"
      repository: "ds2/enterpriselinux-rust"
    steps:
      - name: checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: check modified files
        id: check_files
        run: |
          run_job=false
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo "checking file $file to be from ${{env.path}}"
            if [[ $file != ${{env.path}}/* ]]; then
              echo "ignoring.."
            else
              echo "found changes!"
              run_job=true
              break
            fi
          done < files.txt
          echo "Outcome will be set to: $run_job"
          echo "run_job=$run_job" >> $GITHUB_OUTPUT
      - name: Buildah Action
        id: build-image-buildah
        if: steps.check_files.outputs.run_job == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.repository }}
          context: ./${{ env.path }}
          tags: latest alm9-${{ github.sha }} almalinux9
          build-args: |
            distroVersion=9
            linuxDistro=almalinux
          containerfiles: |
            ./${{ env.path }}/Containerfile
          labels: |
            build_on:github
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        if: ${{ env.registry && steps.build-image-buildah.outputs.image && steps.build-image-buildah.outcome == 'success' }}
        with:
          image: ${{ steps.build-image-buildah.outputs.image }}
          tags: ${{ steps.build-image-buildah.outputs.tags }}
          registry: ${{env.registry}}
          username: ${{ secrets.QUAY_IO_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_IO_REGISTRY_PASSWORD }}
      - name: Print image url
        if: ${{steps.push-to-quay.outcome == 'success'}}
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
  publish-rust-debian:
    name: Publish Debian Rust Image
    runs-on: ubuntu-22.04
    env:
      path: "rust-debian"
      registry: "quay.io"
      repository: "ds2/rust-debian"
    steps:
      - name: checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - name: check modified files
        id: check_files
        run: |
          run_job=false
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo "checking file $file to be from ${{env.path}}"
            if [[ $file != ${{env.path}}/* ]]; then
              echo "ignoring.."
            else
              echo "found changes!"
              run_job=true
              break
            fi
          done < files.txt
          echo "Outcome will be set to: $run_job"
          echo "run_job=$run_job" >> $GITHUB_OUTPUT
      - name: Buildah Action
        id: build-image-buildah
        if: steps.check_files.outputs.run_job == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.repository }}
          context: ./${{ env.path }}
          tags: latest bw-${{ github.sha }} bookworm
          containerfiles: |
            ./${{ env.path }}/Containerfile
          labels: |
            build_on:github
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        if: ${{ env.registry && steps.build-image-buildah.outputs.image && steps.build-image-buildah.outcome == 'success' }}
        with:
          image: ${{ steps.build-image-buildah.outputs.image }}
          tags: ${{ steps.build-image-buildah.outputs.tags }}
          registry: ${{env.registry}}
          username: ${{ secrets.QUAY_IO_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_IO_REGISTRY_PASSWORD }}
      - name: Print image url
        if: ${{steps.push-to-quay.outcome == 'success'}}
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
  publish-quay:
    name: Publish container images
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        containers:
          [
            {
              path: "package-cloud",
              registry: "quay.io",
              repository: "ds2/packagecloud-cli",
            },
          ]
    steps:
      - name: checkout project ${{matrix.containers.path}}
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
          run_job=false
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo "checking file $file to be from ${{matrix.containers.path}}"
            if [[ $file != ${{matrix.containers.path}}/* ]]; then
              echo "ignoring.."
            else
              echo "found changes!"
              run_job=true
              break
            fi
          done < files.txt
          echo "Outcome will be set to: $run_job"
          echo "run_job=$run_job" >> $GITHUB_OUTPUT
      - name: Buildah Action
        id: build-image-buildah
        if: steps.check_files.outputs.run_job == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.containers.repository || matrix.containers.path }}
          context: ./${{ matrix.containers.path }}
          tags: latest ${{ github.sha }}
          # build-args: |
          #   distroVersion=9
          #   linuxDistro=oraclelinux
          containerfiles: |
            ./${{ matrix.containers.path }}/Containerfile
          labels: |
            build_on:github
      - name: Push To Registry
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        if: ${{ matrix.containers.registry && steps.build-image-buildah.outputs.image && steps.build-image-buildah.outcome == 'success' }}
        with:
          image: ${{ steps.build-image-buildah.outputs.image }}
          tags: ${{ steps.build-image-buildah.outputs.tags }}
          registry: ${{matrix.containers.registry}}
          username: ${{ secrets.QUAY_IO_REGISTRY_USERNAME }}
          password: ${{ secrets.QUAY_IO_REGISTRY_PASSWORD }}
      - name: Print image url
        if: ${{steps.push-to-quay.outcome == 'success'}}
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
